import type { Repo, CategoryTemplate } from '../engine/types'
import type { CategoryGroup } from '../components/CategoryGroups.vue'

/**
 * Export current dashboard view as a Markdown report.
 * Triggers a browser download.
 */
export function useMarkdownExport() {
  function exportMarkdown(
    groups: CategoryGroup[],
    meta: {
      username: string
      generatedAt: string
      total: number
      original: number
      fork: number
      star: number
    },
    templateName: string,
    secondaryTemplateName?: string | null
  ): void {
    const lines: string[] = []

    // Header
    lines.push(`# RepoCensus — ${meta.username} 的仓库普查报告`)
    lines.push('')
    lines.push(`> 生成时间：${new Date(meta.generatedAt).toLocaleString('zh-CN')}`)
    lines.push(`> 分类模板：${templateName}${secondaryTemplateName ? ` × ${secondaryTemplateName}` : ''}`)
    lines.push(`> 仓库总数：${meta.total}（自建 ${meta.original} / Fork ${meta.fork} / Star ${meta.star}）`)
    lines.push('')
    lines.push('---')
    lines.push('')

    // Groups
    for (const group of groups) {
      lines.push(`## ${group.name} (${group.count})`)
      lines.push('')

      if (group.subCategories) {
        // Cross-dimension
        for (const sub of group.subCategories) {
          lines.push(`### ${sub.name} (${sub.count})`)
          lines.push('')
          lines.push('| 仓库 | 描述 | 语言 | ⭐ | 类型 |')
          lines.push('|------|------|------|-----|------|')
          for (const repo of sub.repos) {
            const desc = (repo.description || '-').replace(/\|/g, '\\|').replace(/\n/g, ' ')
            const lang = repo.language || '-'
            const type = repo.type === 'original' ? '自建' : repo.type === 'fork' ? 'Fork' : 'Star'
            lines.push(`| [${repo.full_name}](${repo.html_url}) | ${desc} | ${lang} | ${repo.stargazers_count} | ${type} |`)
          }
          lines.push('')
        }
      } else {
        // Single dimension
        lines.push('| 仓库 | 描述 | 语言 | ⭐ | 类型 |')
        lines.push('|------|------|------|-----|------|')
        for (const repo of group.repos || []) {
          const desc = (repo.description || '-').replace(/\|/g, '\\|').replace(/\n/g, ' ')
          const lang = repo.language || '-'
          const type = repo.type === 'original' ? '自建' : repo.type === 'fork' ? 'Fork' : 'Star'
          lines.push(`| [${repo.full_name}](${repo.html_url}) | ${desc} | ${lang} | ${repo.stargazers_count} | ${type} |`)
        }
        lines.push('')
      }
    }

    // Footer
    lines.push('---')
    lines.push('')
    lines.push('*Generated by [RepoCensus](https://github.com/Leoli04/repocensus)*')

    // Download
    const content = lines.join('\n')
    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `repocensus-${meta.username}-${new Date().toISOString().slice(0, 10)}.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return { exportMarkdown }
}
