import type { Repo, CategoryTemplate } from '../engine/types'
import type { CategoryGroup } from '../components/CategoryGroups.vue'
import { useRepos } from './useRepos'
import { useRepoMeta } from './useRepoMeta'

type Row = Repo & { note: string; tags: string[] }

/**
 * Export the current dashboard. Triggers browser downloads.
 * Includes per-repo note & custom tags (from localStorage).
 */
export function useExport() {
  const { data } = useRepos()
  const { allMeta } = useRepoMeta()

  function withMeta(repos: Repo[]): Row[] {
    const m = allMeta()
    return repos.map((r) => {
      const mm = m[String(r.id)] ?? { note: '', tags: [] }
      return { ...r, note: mm.note, tags: mm.tags }
    })
  }

  function download(filename: string, content: string, mime: string) {
    const blob = new Blob([content], { type: mime })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  // ── Markdown ────────────────────────────────────────────
  function exportMarkdown(
    groups: CategoryGroup[],
    meta: {
      username: string
      generatedAt: string
      total: number
      original: number
      fork: number
      star: number
    },
    templateName: string,
    secondaryTemplateName?: string | null
  ): void {
    const lines: string[] = []
    lines.push(`# RepoCensus — ${meta.username} 的仓库普查报告`)
    lines.push('')
    lines.push(`> 生成时间：${new Date(meta.generatedAt).toLocaleString('zh-CN')}`)
    lines.push(`> 分类模板：${templateName}${secondaryTemplateName ? ` × ${secondaryTemplateName}` : ''}`)
    lines.push(`> 仓库总数：${meta.total}（自建 ${meta.original} / Fork ${meta.fork} / Star ${meta.star}）`)
    lines.push('')
    lines.push('---')
    lines.push('')

    const esc = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ')

    for (const group of groups) {
      lines.push(`## ${group.name} (${group.count})`)
      lines.push('')
      const header = '| 仓库 | 描述 | 语言 | ⭐ | 类型 | 笔记 | 标签 |'
      const sep = '|------|------|------|-----|------|------|------|'
      if (group.subCategories) {
        for (const sub of group.subCategories) {
          lines.push(`### ${sub.name} (${sub.count})`)
          lines.push('')
          lines.push(header)
          lines.push(sep)
          for (const repo of sub.repos) {
            const row = withMeta([repo])[0]
            lines.push(
              `| [${repo.full_name}](${repo.html_url}) | ${esc(row.description || '-')} | ${row.language || '-'} | ${row.stargazers_count} | ${row.type} | ${esc(row.note || '-')} | ${esc((row.tags || []).join(', ')) || '-'} |`
            )
          }
          lines.push('')
        }
      } else {
        lines.push(header)
        lines.push(sep)
        for (const repo of group.repos || []) {
          const row = withMeta([repo])[0]
          lines.push(
            `| [${repo.full_name}](${repo.html_url}) | ${esc(row.description || '-')} | ${row.language || '-'} | ${row.stargazers_count} | ${row.type} | ${esc(row.note || '-')} | ${esc((row.tags || []).join(', ')) || '-'} |`
          )
        }
        lines.push('')
      }
    }

    lines.push('---')
    lines.push('')
    lines.push('*Generated by [RepoCensus](https://github.com/Leoli04/repocensus)*')

    download(
      `repocensus-${meta.username}-${new Date().toISOString().slice(0, 10)}.md`,
      lines.join('\n'),
      'text/markdown;charset=utf-8'
    )
  }

  // ── JSON ────────────────────────────────────────────────
  function exportJSON(): void {
    const repos = withMeta(data.value.repos)
    const payload = {
      username: data.value.username,
      generated_at: data.value.generated_at,
      stats: data.value.stats,
      repos: repos.map(({ note, tags, ...r }) => ({ ...r, note, tags })),
    }
    download(
      `repocensus-${data.value.username}.json`,
      JSON.stringify(payload, null, 2),
      'application/json;charset=utf-8'
    )
  }

  // ── CSV ─────────────────────────────────────────────────
  function exportCSV(): void {
    const repos = withMeta(data.value.repos)
    const header = [
      'full_name', 'name', 'description', 'language', 'stars', 'forks',
      'type', 'category', 'health', 'updated_at', 'created_at', 'note', 'tags',
    ]
    const cell = (s: unknown) => `"${String(s ?? '').replace(/"/g, '""')}"`
    const rows = repos.map((r) =>
      [
        r.full_name, r.name, r.description || '', r.language || '', r.stargazers_count,
        r.forks_count, r.type, r.category, r.health_score, r.updated_at, r.created_at,
        r.note || '', (r.tags || []).join('|'),
      ].map(cell).join(',')
    )
    const csv = [header.map(cell).join(','), ...rows].join('\n')
    // BOM so Excel reads UTF-8 correctly
    download(`repocensus-${data.value.username}.csv`, '﻿' + csv, 'text/csv;charset=utf-8')
  }

  return { exportMarkdown, exportJSON, exportCSV }
}
